### ISSUE TITLE
Question about building etls on Travis CI, when used in Elixir projects

### ISSUE THREAD

**Issue by florinpatrascu** [kzemek/erlang_tls#12]
Hi there - thank you for your work on ETLS. Can you please provide some hints about building etls in a Travis CI test environment? I just integrated ETLS in my project [Bolt.Sips](https://github.com/florinpatrascu/bolt_sips) but am unable to pass a travis build due to missing dependencies doing lets build. I even tried using a variant of your `travis.yml` config file, with no success. Anybody having the same issue, and have a recipe to share? Many thanks, and Happy Holidays!

**Comment by kzemek** [comment]
Unfortunately, Travis is a little finicky about up-to-date build requirements. The problem you had in [this build](https://travis-ci.org/florinpatrascu/bolt_sips/jobs/186559038) can be solved by adding global envs `CXX=g++-6` and `CC=gcc-6`.

You can remove the test matrix; Travis cannot parse it probably because it doesn't understand `otp_release: x` in conjunction with `language: elixir`. Some of the APT packages are also unneeded when using etls as dependency.

[Here's a trimmed down config diff](https://gist.github.com/kzemek/3473adb267d69570df389fa9e4154e2b) (against [0b34fee](https://github.com/florinpatrascu/bolt_sips/commit/0b34fee0a18d4af34e27c78292c8a8d1da76e4b9)) that I confirmed works with your repo. :)

**Comment by florinpatrascu** [comment]
Thank you very much indeed. Now I understand better all this build process, and I can use Travis again in my project. Thanks so much, for your help, highly appreciated!
